In [2]:
import numpy as np
import pandas as pd

xlsx = pd.ExcelFile(r"E:\文件\代码积累\python\a积累代码\Topsis\20条河流的水质情况数据.xlsx")
data_pd = pd.read_excel(xlsx, 'Sheet1')
data_pd.set_index('河流', inplace=True)# 将"河流"列设置为索引，并替换原DataFrame
data_pd

含氧量（ppm)   PH值  细菌总数(个/mL)  植物性营养物量（ppm)
河流                                          
A       4.69  6.59          51         11.94
B       2.03  7.86          19          6.46
C       9.11  6.31          46          8.91
D       8.61  7.05          46         26.43
E       7.13  6.50          50         23.57
F       2.39  6.77          38         24.62
G       7.69  6.79          38          6.01
H       9.30  6.81          27         31.57
I       5.45  7.62           5         18.46
J       6.19  7.27          17          7.51
K       7.93  7.53           9          6.52
L       4.40  7.28          17         25.30
M       7.46  8.24          23         14.42
N       2.01  5.55          47         26.31
O       2.04  6.40          23         17.91
P       7.73  6.14          52         15.72
Q       6.35  7.58          25         29.46
R       8.29  8.41          39         12.02
S       3.54  7.27          54          3.16
T       7.44  6.26           8         28.41

In [33]:
data = np.asarray(data_pd)
data

array([[ 4.69,  6.59, 51.  , 11.94],
       [ 2.03,  7.86, 19.  ,  6.46],
       [ 9.11,  6.31, 46.  ,  8.91],
       [ 8.61,  7.05, 46.  , 26.43],
       [ 7.13,  6.5 , 50.  , 23.57],
       [ 2.39,  6.77, 38.  , 24.62],
       [ 7.69,  6.79, 38.  ,  6.01],
       [ 9.3 ,  6.81, 27.  , 31.57],
       [ 5.45,  7.62,  5.  , 18.46],
       [ 6.19,  7.27, 17.  ,  7.51],
       [ 7.93,  7.53,  9.  ,  6.52],
       [ 4.4 ,  7.28, 17.  , 25.3 ],
       [ 7.46,  8.24, 23.  , 14.42],
       [ 2.01,  5.55, 47.  , 26.31],
       [ 2.04,  6.4 , 23.  , 17.91],
       [ 7.73,  6.14, 52.  , 15.72],
       [ 6.35,  7.58, 25.  , 29.46],
       [ 8.29,  8.41, 39.  , 12.02],
       [ 3.54,  7.27, 54.  ,  3.16],
       [ 7.44,  6.26,  8.  , 28.41]])

## 第一步：判断是否需要正向化,并正向化


In [34]:
n, m = data.shape
print("共有{}个评价对象，{}个评价指标".format(n,m))

共有20个评价对象，4个评价指标


In [35]:
def forwarding(series, f_row, f_type):
    if f_type == 1:
        print("第{}列是极小型，正在正向化".format(f_row))
        series = np.max(series) - series
        print("完成")
        return series
    elif f_type == 2:
        print("第{}列是中间型，正在正向化".format(f_row))
        best = float(input("请输入最佳的值"))
        D = np.abs(series - best).max()
        series = 1 - np.abs(series - best) / D
        print("完成")
        return series
    elif f_type == 3:
        print("第{}列是区间型，正在正向化".format(f_row))
        a = float(input("请输入区间的下界"))
        b = float(input("请输入区间的上界"))
        D = max(a - series.min(), series.max() - b)
        for i in range(len(series)):
            element = series[i]
            if element < a:
                series[i] = 1 - (a - element) / D
            elif element > b:
                series[i] = 1 - (element - b) / D
            else:
                series[i] = 1
        print("完成")
        return series

In [36]:
#设置正向化指标，将所有指标转换为极大型指标
judge_row = [2,3,4] #输入需要正向化处理的指标所在的列，例如第1、4、7列需要处理，那么设置为[1，4，7]
judge_row = [i - 1 for i in judge_row]
judge_type = [2,1,3]#输入需要处理的列的指标的类型（1：极小型，2：中间型，3：区间型）
for i in range(len(judge_row)):
    data[:,judge_row[i]] = forwarding(data[:,judge_row[i]],judge_row[i], judge_type[i])
data

第1列是中间型，正在正向化
请输入最佳的值7
完成
第2列是极小型，正在正向化
完成
第3列是区间型，正在正向化
请输入区间的下界10
请输入区间的上界20
完成


array([[4.69000000e+00, 7.17241379e-01, 3.00000000e+00, 1.00000000e+00],
       [2.03000000e+00, 4.06896552e-01, 3.50000000e+01, 6.94036301e-01],
       [9.11000000e+00, 5.24137931e-01, 8.00000000e+00, 9.05790838e-01],
       [8.61000000e+00, 9.65517241e-01, 8.00000000e+00, 4.44252377e-01],
       [7.13000000e+00, 6.55172414e-01, 4.00000000e+00, 6.91443388e-01],
       [2.39000000e+00, 8.41379310e-01, 1.60000000e+01, 6.00691443e-01],
       [7.69000000e+00, 8.55172414e-01, 1.60000000e+01, 6.55142610e-01],
       [9.30000000e+00, 8.68965517e-01, 2.70000000e+01, 0.00000000e+00],
       [5.45000000e+00, 5.72413793e-01, 4.90000000e+01, 1.00000000e+00],
       [6.19000000e+00, 8.13793103e-01, 3.70000000e+01, 7.84788245e-01],
       [7.93000000e+00, 6.34482759e-01, 4.50000000e+01, 6.99222126e-01],
       [4.40000000e+00, 8.06896552e-01, 3.70000000e+01, 5.41918755e-01],
       [7.46000000e+00, 1.44827586e-01, 3.10000000e+01, 1.00000000e+00],
       [2.01000000e+00, 0.00000000e+00, 7.00000000e

## 第二步：对正向化后的矩阵进行标准化
$$
z_{ij}\,\,=\,\,\frac{x_{ij}}{\sqrt{\sum_{i=1}^n{x_{ij}^{2}}}}
$$

In [37]:
data_n = data/np.sqrt(np.sum(data * data,axis = 0)).reshape(1,m) #按照上面公式进行数据处理
data_n

array([[0.16218592, 0.24825528, 0.02454403, 0.30645756],
       [0.07019987, 0.14083713, 0.28634707, 0.21269267],
       [0.3150349 , 0.18141732, 0.06545076, 0.27758645],
       [0.29774429, 0.3341898 , 0.06545076, 0.1361445 ],
       [0.24656409, 0.22677165, 0.03272538, 0.21189806],
       [0.08264911, 0.29122254, 0.13090152, 0.18408644],
       [0.26592957, 0.29599668, 0.13090152, 0.20077341],
       [0.32160534, 0.30077082, 0.22089631, 0.        ],
       [0.18846764, 0.19812681, 0.4008859 , 0.30645756],
       [0.21405774, 0.28167426, 0.30270976, 0.24050429],
       [0.27422907, 0.21961044, 0.36816052, 0.21428191],
       [0.15215736, 0.27928719, 0.30270976, 0.1660751 ],
       [0.25797589, 0.05012847, 0.25362169, 0.30645756],
       [0.06950825, 0.        , 0.05726941, 0.13932297],
       [0.07054569, 0.20290095, 0.25362169, 0.30645756],
       [0.26731282, 0.14083713, 0.01636269, 0.30645756],
       [0.21959074, 0.20767509, 0.237259  , 0.05588811],
       [0.2866783 , 0.00954828,

## 第三步：计算与最大值的距离和最小值的距离，并算出得分


In [38]:
data_max = data_n.max(axis = 0).reshape(1,m) #定义最大值
data_min = data_n.min(axis = 0).reshape(1,m) #定义最小值

D_max = np.sum(np.square(data_n-data_max),axis=1)  ** 0.5
D_min = np.sum(np.square(data_n-data_min),axis=1)  ** 0.5
S = D_min/(D_max+D_min)
stand_S = S/np.sum(S)
stand_S = pd.Series(stand_S,index = data_pd.index)
stand_S = stand_S.sort_values(ascending = False)
stand_S

河流
K    0.070162
J    0.068393
I    0.068074
L    0.059093
T    0.056466
G    0.053947
O    0.053307
M    0.052652
H    0.050998
D    0.048820
C    0.048497
B    0.047799
Q    0.046574
A    0.045058
F    0.044838
R    0.043844
P    0.043359
E    0.043113
S    0.035810
N    0.019196
dtype: float64