In [1]:
import numpy as np

def floyd(graph, a, b):
    n = len(graph)
    # 使用numpy初始化
    distance = np.array(graph)
    # 初始化路由矩阵
    route = np.zeros((n, n), dtype=int)
    for i in range(n):
        for j in range(n):
            if graph[i][j] != float('inf') and i != j:
                route[i][j] = j

    # 开始迭代
    for center in range(n):
        for start in range(n):
            for end in range(n):
                if distance[start][center] + distance[center][end] < distance[start][end]:
                    route[start][end] = route[start][center]
                    distance[start][end] = distance[start][center] + distance[center][end]
    route_d = get_route(route, a, b)
    return distance, route, route_d, distance[a-1][b-1]

def get_route(route, a, b):
    path = [a]
    current = a - 1
    while current != b - 1:
        next_hop = route[current][b - 1]
        path.append(next_hop + 1)
        current = next_hop
    return path

matrix = [[0, float('inf'), float('inf'), 1.2, 9.2, float('inf'), float('inf')],
          [float('inf'), 0, float('inf'), 5, float('inf'), 3.1, 2],
          [float('inf'), float('inf'), 0, float('inf'), float('inf'), 4, 1.5],
          [1.2, 5, float('inf'), 0, 6.7, float('inf'), float('inf')],
          [9.2, float('inf'), float('inf'), 6.7, 0, 15.6, float('inf')],
          [float('inf'), 3.1, 4, float('inf'), 15.6, 0, float('inf')],
          [float('inf'), 2, 1.5, float('inf'), float('inf'), float('inf'), 0]]
a = 3
b = 5
graph, route, route_d, distance = floyd(matrix, a, b)

print("Distance:", distance)
print("Route_d:", route_d)
print("Route:", np.array(route))


Distance: 15.2
Route_d: [3, 7, 2, 4, 5]
Route: [[0 3 3 3 3 3 3]
 [3 0 6 3 3 5 6]
 [6 6 0 6 6 5 6]
 [0 1 1 0 4 1 1]
 [3 3 3 3 0 3 3]
 [1 1 2 1 1 0 1]
 [1 1 2 1 1 1 0]]
